MembersInformationApp/Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MembersInformationApp.Models
{
    public class Member
    {        
        [Display(Name = "Member ID")]
        public int MemberID { get; set; }

        [Required(ErrorMessage = "First Name Required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name Required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email ID Required")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Display(Name = "Date of Birth")]
        [Required(ErrorMessage = "Date Of Birth Required")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime DateOfBirth { get; set; }
    }
}

MembersInformationApp/Controllers/MembersController.cs
using MembersInformationApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MembersInformationApp.Controllers
{
    public class MembersController : Controller
    {
        private string Base_URL = "http://localhost:58122/";

        public ActionResult Index()
        {
            List<Member> MemberInfo = new List<Member>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Base_URL);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = client.GetAsync("api/GetMember").Result;
                if (response.IsSuccessStatusCode)
                {
                    var MemberResponse = response.Content.ReadAsStringAsync().Result;
                    MemberInfo = JsonConvert.DeserializeObject<List<Member>>(MemberResponse);
                    response = client.GetAsync("api/GetOldestMember").Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var OldestMemberResponse = response.Content.ReadAsStringAsync().Result;
                        Member objMember = JsonConvert.DeserializeObject<Member>(OldestMemberResponse);
                        int age = CalculateAge(objMember.DateOfBirth);
                        ViewBag.OldestMemberInfo = objMember.FirstName + "," + objMember.LastName + "," + age;
                    }                    
                }               
                return View(MemberInfo);
            }
        }

        public ActionResult Create(Member member)
        {
            List<Member> MemberInfo = new List<Member>();
            if (ModelState.IsValid)
            {                
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Base_URL);
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage response = client.PostAsJsonAsync("api/PostMember", member).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        response = client.GetAsync("api/GetMember").Result;
                        if (response.IsSuccessStatusCode)
                        {
                            var MemberResponse = response.Content.ReadAsStringAsync().Result;
                            MemberInfo = JsonConvert.DeserializeObject<List<Member>>(MemberResponse);
                            response = client.GetAsync("api/GetOldestMember").Result;
                            if (response.IsSuccessStatusCode)
                            {
                                var OldestMemberResponse = response.Content.ReadAsStringAsync().Result;
                                Member objMember = JsonConvert.DeserializeObject<Member>(OldestMemberResponse);
                                int age = CalculateAge(objMember.DateOfBirth);
                                ViewBag.OldestMemberInfo = objMember.FirstName + "," + objMember.LastName + "," + age;
                            }
                        }
                    }
                }
                return View("Index", MemberInfo);
            }
            else
            {                
                return RedirectToAction("Index");
            }               
        }

        private static int CalculateAge(DateTime dateOfBirth)
        {
            int age = 0;
            age = DateTime.Now.Year - dateOfBirth.Year;
            if (DateTime.Now.DayOfYear < dateOfBirth.DayOfYear)
                age = age - 1;

            return age;
        }
    }       
}

MembersInformationApp/Views/Members/Index.cshtml
@model IEnumerable<MembersInformationApp.Models.Member>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        table {
            border: solid;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $("#DateOfBirth").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0",
                dateFormat: 'dd-M-yy'
            });           
        
            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };

        });
    </script>    
</head>
<body>
    @using (Html.BeginForm("Create", "Members", FormMethod.Post))
    {        
        <table style="border:none">
            <tr style="background-color:white">
                <td>
                    First Name: @Html.TextBox("FirstName")                    
                <td>
                    Email:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Html.TextBox("Email")                    
                </td>
            </tr>
            <tr style="background-color:white">
                <td>
                    Last Name: @Html.TextBox("LastName")                   
                </td>
                <td>
                    Date of Birth: @Html.Editor("DateOfBirth")                   
                </td>
            </tr>
            <tr style="background-color:white">
                <td></td>
                <td>
                    <input type="submit" value="Add" />
                </td>
            </tr>
        </table>
    }
    <br />
    <br />
    <table class="table" align="center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MemberID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
            </tr>
        }

    </table>
    <br/>
    <br/>
    <table style="border:none">
        <tr>
            <td style="font:bold">
                Oldest Member: @ViewBag.OldestMemberInfo
            </td>
        </tr>
    </table>

</body>
</html>